const prefix = 'COURIER_ORDERS_';

export default {
  FETCH_COURIER_ORDERS: `${prefix}FETCH_COURIER_ORDERS`,
  FETCH_COURIER_ORDERS_COMPLETED: `${prefix}FETCH_COURIER_ORDERS_COMPLETED`,
  SET_ORDER_TYPE: `${prefix}SET_ORDER_TYPE`,
};
