module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['@babel/plugin-proposal-decorators', {legacy: true}],
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: true,
        regenerator: false,
      },
    ],
    [
      'module-resolver',
      {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        root: ['./'],
        alias: {
          'resources': ['./resources'],
          'app/shared': ['./shared/src/app'],
          'app/client': ['./client/src/app'],
          'app/courier': ['./courier/src/app'],
          'app/restaurant': ['./restaurant/src/app'],
          'app': ['./shared/src/app', './client/src/app'],
          'api': ['./shared/src/api'],
          'entities/shared': ['./shared/src/entities'],
          'entities': [
            './shared/src/entities',
            './client/src/entities',
            './courier/src/entities',
            './restaurant/src/entities',
          ],
          'localization': ['./client/src/localization'],
          'navigation/shared': ['./shared/src/navigation'],
          'navigation/client': ['./client/src/navigation'],
          'navigation/courier': ['./courier/src/navigation'],
          'navigation/restaurant': ['./restaurant/src/navigation'],
          'navigation': ['./shared/src/navigation', './client/src/navigation'],
          'components/shared': ['./shared/src/components'],
          'components': ['./shared/src/components'],
          'hooks': ['./client/src/hooks'],
          'routes/shared': ['./shared/src/routes'],
          'routes/client': ['./client/src/routes'],
          'routes': [
            './shared/src/routes',
            './client/src/routes',
            './courier/src/routes',
            './restaurant/src/routes',
          ],
          'state/shared': ['./shared/src/state'],
          'state/client': ['./client/src/state'],
          'state/courier': ['./courier/src/state'],
          'state/restaurant': ['./restaurant/src/state'],
          'screens/restaurant': ['./restaurant/src/screens'],
          'state': ['./shared/src/state', './client/src/state'],
          'utils': ['./shared/src/utils'],
          'auth': ['./shared/src/auth'],
          'services': ['./shared/src/services', './client/src/services'],
        },
      },
    ],
  ],
};
