const prefix = 'COURIER_ORDERS_';

export default {
  FETCH_CURRENT_RESTAURANT: `${prefix}FETCH_CURRENT_RESTAURANT`,
  FETCH_CURRENT_RESTAURANT_COMPLETED: `${prefix}FETCH_CURRENT_RESTAURANT_COMPLETED`,
};
