const prefix = 'SETS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_SETS: `${prefix}FETCH_SETS`,
  FETCH_SETS_COMPLETED: `${prefix}FETCH_SETS_COMPLETED`,
  FETCH_SETS_BY_DISH_ID: `${prefix}FETCH_SETS_BY_DISH_ID`,
  FETCH_SETS_BY_DISH_ID_COMPLETED: `${prefix}FETCH_SETS_BY_DISH_ID_COMPLETED`,
  FETCH_SETS_BY_CUISINE_ID: `${prefix}FETCH_SETS_BY_CUISINE_ID`,
  FETCH_SETS_BY_CUISINE_ID_COMPLETED: `${prefix}FETCH_SETS_BY_CUISINE_ID_COMPLETED`,
  ADD_SET_TO_SELECTED_DAY: `${prefix}ADD_SET_TO_SELECTED_DAY`,
  DELETE_SET_FROM_SELECTED_DAY: `${prefix}DELETE_SET_FROM_SELECTED_DAY`,
  DISTRIBUTE_SETS_BY_DAYS: `${prefix}DISTRIBUTE_SETS_BY_DAYS`,
  DISTRIBUTE_SETS_BY_DAYS_COMPLETED: `${prefix}DISTRIBUTE_SETS_BY_DAYS_COMPLETED`,
  CLEAR: `${prefix}CLEAR`,
};
