const prefix = 'ORDER_PROGRESS_';

export default {
  FETCH_ORDER: `${prefix}FETCH_ORDER`,
  ORDER: `${prefix}ORDER`,
  UPDATE_ORDER_PROGRESS: `${prefix}UPDATE_ORDER_PROGRESS`,
  ORDER_FETCHED: `${prefix}ORDER_FETCHED`,
  SCAN_BAGS: `${prefix}SCAN_BAGS`,
  CONFIRM_PAYMENT: `${prefix}CONFIRM_PAYMENT`,
  PAY_FOR_ORDER: `${prefix}PAY_FOR_ORDER`,
  PAY_FOR_ORDER_COMPLETED: `${prefix}PAY_FOR_ORDER_COMPLETED`,
  CONFIRM_DELETE_ORDER: `${prefix}CONFIRM_DELETE_ORDER`,
  DELETE_ORDER: `${prefix}DELETE_ORDER`,
  DELETE_ORDER_COMPLETED: `${prefix}DELETE_ORDER_COMPLETED`,
  CONFIRM_BAGS: `${prefix}CONFIRM_BAGS`,
  ACCEPT_SCAN: `${prefix}ACCEPT_SCAN`,
  PAY_FOR_WASHING: `${prefix}PAY_FOR_WASHING`,
  PAY_FOR_WASHING_COMPLETED: `${prefix} PAY_FOR_WASHING_COMPLETED`,
  FETCH_COURIER_LOCATION: `${prefix}FETCH_COURIER_LOCATION`,
  FETCH_COURIER_LOCATION_COMPLETE: `${prefix}FETCH_COURIER_LOCATION_COMPLETE`,
};
