const prefix = 'SESSION_';

export default {
  FETCH_SESSION: `${prefix}FETCH_SESSION`,
  SET_SESSION_EXISTS: `${prefix}SET_SESSION_EXISTS`,
  FETCH_USER_ACCOUNT: `${prefix} FETCH_USER_ACCOUNT`,
  FETCH_USER_COMPLETED: `${prefix}FETCH_USER_COMPLETED`,
  UPDATE_USER_PROFILE: `${prefix}UPDATE_USER_PROFILE`,
  UPDATE_USER_PROFILE_COMPLETED: `${prefix}UPDATE_USER_PROFILE_COMPLETED`,
  UPDATE_PROFILE_IMAGE: `${prefix}UPDATE_PROFILE_IMAGE`,
  UPDATE_PROFILE_IMAGE_COMPLETED: `${prefix}UPDATE_PROFILE_IMAGE_COMPLETED`,
};
