const prefix = 'AUTH_';

export default {
  REGISTER_USER: `${prefix}REGISTER_USER`,
  LOGIN_USER: `${prefix}LOGIN_USER`,
  AUTH_COMPLETED: `${prefix}AUTH_COMPLETED`,
  LOGOUT: `${prefix}LOGOUT`,
  RECOVER_PASSWORD: `${prefix}RECOVER_PASSWORD`,
  RECOVER_PASSWORD_COMPLETED: `${prefix}RECOVER_PASSWORD_COMPLETED`,
  UPLOAD_FILE_USER: `${prefix}UPLOAD_FILE_USER`,
  SET_IS_CHECKING: `${prefix}SET_IS_CHECKING`,
  CHOOSE_AVATAR: `${prefix}CHOOSE_AVATAR`,
  CHOOSE_AVATAR_COMPLETED: `${prefix}CHOOSE_AVATAR_COMPLETED`,
};
