const prefix = 'STATUS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  UPDATE_STATUS: `${prefix}UPDATE_STATUS`,
  UPDATE_STATUS_COMPLETED: `${prefix}UPDATE_STATUS_COMPLETED`,
  CREATE_STATUS: `${prefix}CREATE_STATUS`,
  CREATE_STATUS_COMPLETED: `${prefix}CREATE_STATUS_COMPLETED`,
  DELETE_STATUS: `${prefix}DELETE_STATUS`,
  CLEAR: `${prefix}CLEAR`,
  SUBMIT: `${prefix}SUBMIT`,
};
