const prefix = 'LOCATION_';

export default {
  LOCATION_UPDATED: `${prefix}LOCATION_UPDATED`,
  REQUEST_LOCATION_PERMISSION: `${prefix}REQUEST_LOCATION_PERMISSION`,
  CHECK_LOCATION_PERMISSION_ALWAYS: `${prefix}CHECK_LOCATION_PERMISSION_ALWAYS`,
  LOCATION_PERMISSION_ALWAYS_CHECKED: `${prefix}LOCATION_PERMISSION_ALWAYS_CHECKED`,
  OPEN_SETTINGS: `${prefix}OPEN_SETTINGS`,
};
