const prefix = 'CLIENTS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  UPDATE_CLIENT_INFORMATION: `${prefix}UPDATE_CLIENT_INFORMATION`,
  UPDATE_CLIENT_INFORMATION_COMPLETED: `${prefix}UPDATE_CLIENT_INFORMATION_COMPLETED`,
  SUBMIT: `${prefix}SUBMIT`,
};
