const prefix = 'ORDER_PROGRESS_';

export default {
  FETCH_ORDER: `${prefix}FETCH_ORDER`,
  ORDER_FETCHED: `${prefix}ORDER_FETCHED`,
  TO_ORDERS_LIST: `${prefix}TO_ORDERS_LIST`,
  OPEN_NAVIGATOR: `${prefix}OPEN_NAVIGATOR`,
  SCAN_BAGS: `${prefix}SCAN_BAGS`,
  CONFIRM_BAGS: `${prefix}CONFIRM_BAGS`,
  ACCEPT_SCAN: `${prefix}ACCEPT_SCAN`,
  ACCEPT_SCAN_COMPLETED: `${prefix}ACCEPT_SCAN_COMPLETED`,
  REQUEST_CURRENT_POSITION: `${prefix}REQUEST_CURRENT_POSITION`,
  MY_ORDER_FETCHED: `${prefix}MY_ORDER_FETCHED`,
  FETCH_COURIER_LOCATION: `${prefix}FETCH_COURIER_LOCATION`,
  FETCH_COURIER_LOCATION_COMPLETE: `${prefix}FETCH_COURIER_LOCATION_COMPLETE`,
};
