const prefix = 'ROUTER_COURIER_';

export default {
  GO_BACK: `${prefix}GO_BACK`,
  NAVIGATE_TO_MAIN: `${prefix}NAVIGATE_TO_MAIN`,
  NAVIGATE_TO_CURRENT_ORDERS: `${prefix}NAVIGATE_TO_CURRENT_ORDERS`,
  NAVIGATE_TO_ORDER_DETAILS: `${prefix}NAVIGATE_TO_ORDER_DETAILS`,
  NAVIGATE_TO_ORDER_PROGRESS: `${prefix}NAVIGATE_TO_ORDER_PROGRESS`,
  NAVIGATE_TO_PROFILE: `${prefix}NAVIGATE_TO_PROFILE`,
  NAVIGATE_TO_SCANNER: `${prefix}NAVIGATE_TO_SCANNER`,
};
