const prefix = 'SCANNER_';

export default {
  INIT_SCANNER: `${prefix}INIT_SCANNER`,
  INIT_SCANNER_COMPLETED: `${prefix}INIT_SCANNER_COMPLETED`,
  CODE_RECEIVED: `${prefix}CODE_RECEIVED`,
  PROCESS_CODE: `${prefix}PROCESS_CODE`,
  PROCESS_CODE_COMPLETED: `${prefix}PROCESS_CODE_COMPLETED`,
  DELETE_BAG: `${prefix}DELETE_BAG`,
  CONFIRM: `${prefix}CONFIRM`,
  RESET_PROCESSING: `${prefix}RESET_PROCESSING`,
  SCAN_BAGS: `${prefix}SCAN_BAGS`,
  CONFIRM_BAGS: `${prefix}CONFIRM_BAGS`,
  ACCEPT_SCAN: `${prefix}ACCEPT_SCAN`,
  ACCEPT_SCAN_COMPLETED: `${prefix}ACCEPT_SCAN_COMPLETED`,
};
