const prefix = 'ROUTER_SHARED_';

export default {
  GO_BACK: `${prefix}GO_BACK`,
  ACCOUNT_ENTERED: `${prefix}ACCOUNT_ENTERED`,
  NAVIGATE_TO_AUTH: `${prefix}NAVIGATE_TO_AUTH`,
  NAVIGATE_TO_MAIN: `${prefix}NAVIGATE_TO_MAIN `,
  NAVIGATE_TO_CHANGE_PASSWORD: `${prefix}NAVIGATE_TO_CHANGE_PASSWORD`,
  NAVIGATE_TO_IMAGE_PICKER: `${prefix}NAVIGATE_TO_IMAGE_PICKER`,
  NAVIGATE_TO_SETTINGS: `${prefix}NAVIGATE_TO_SETTINGS`,
  MAIN_ENTERED: `${prefix}MAIN_ENTERED`,
  NAVIGATE_TO_ORDER_POPUP: `${prefix}NAVIGATE_TO_ORDER_POPUP`,
  SCANNER_ENTERED: `${prefix}SCANNER_ENTERED`,
  NAVIGATE_TO_ORDER_HISTORY: `${prefix} NAVIGATE_TO_ORDER_HISTORY`,
  ORDER_HISTORY_ENTERED: `${prefix}ORDER_HISTORY_ENTERED`,
  NAVIGATE_TO_ORDER_DETAILS: `${prefix}NAVIGATE_TO_ORDER_DETAILS`,
  NAVIGATE_TO_CLIENT_DETAILS: `${prefix}NAVIGATE_TO_CLIENT_DETAILS`,
  NAVIGATE_TO_COURIER_DETAILS: `${prefix}NAVIGATE_TO_COURIER_DETAILS`,
  NAVIGATE_TO_RESTAURANT_DETAILS: `${prefix}NAVIGATE_TO_RESTAURANT_DETAILS`,
  NAVIGATE_TO_PAYMENT_DETAILS: `${prefix}NAVIGATE_TO_PAYMENT_DETAILS`,
  NAVIGATE_TO_CREATE_OR_UPDATE_PAGE: `${prefix}NAVIGATE_TO_CREATE_OR_UPDATE_PAGE`,
};
