const prefix = 'DISH_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  UPDATE_DISH: `${prefix}UPDATE_DISH`,
  UPDATE_DISH_COMPLETED: `${prefix}UPDATE_DISH_COMPLETED`,
  CREATE_DISH: `${prefix}CREATE_DISH`,
  CREATE_DISH_COMPLETED: `${prefix}CREATE_DISH_COMPLETED`,
  DELETE_DISH: `${prefix}DELETE_DISH`,
  CLEAR: `${prefix}CLEAR`,
  SUBMIT: `${prefix}SUBMIT`,
};
