const prefix = 'COURIER_DOCUMENTS_';

export default {
  CHOOSE_DOCUMENT: `${prefix}CHOOSE_DOCUMENT`,
  FETCH_DOCUMENTS: `${prefix}FETCH_DOCUMENTS`,
  FETCH_DOCUMENTS_COMPLETED: `${prefix}FETCH_DOCUMENTS_COMPLETED`,
  ADD_DOCUMENT: `${prefix}ADD_DOCUMENT`,
  DELETE_DOCUMENT: `${prefix}DELETE_DOCUMENT`,
  SUBMIT: `${prefix}SUBMIT`,
  CONFIRM_SUBMIT: `${prefix}CONFIRM_SUBMIT`,
  IMAGE_PICKER_PICK: `${prefix}IMAGE_PICKER_PICK`,
};
